build:
    tests:
        override:
            -
                command: go test -coverprofile=cover.out
                coverage:
                    file: 'cover.out'
                    format: 'go-cc'